version: "2.1"

services:
  springboot-test:
    build:
      context: .
      dockerfile: Docker/springboot-test/Dockerfile
    image: "springboot-test_image"
    container_name: "springboot-test_container"
    depends_on:
      springboot:
        condition: service_healthy
    
  springboot:
    build:
      context: .
      dockerfile: Docker/springboot/Dockerfile
    restart: "always"
    image: "springboot_image"
    container_name: "springboot_container"
    ports:
    - "8080:8080"
    healthcheck:
        test: "exit 0"
        interval: 20s
        timeout: 10s
        retries: 5
    depends_on:
    - "mongo"

  mongo:
    build:
      context: .
      dockerfile: Docker/mongo/Dockerfile
    image: "mongodb_image"
    container_name: "mongodb_container"
    ports:
    - "27017:27017"
    restart: "always"
